
# NumPy — Guida pratica con esempi (da zero ad operativo)
**Contenuti**: array n‑dimensionali, slicing, ufunc, aggregazioni, ordinamento, algebra, broadcasting, indexing avanzato, concatenazione/split/reshape e gestione dimensioni.

> Notebook generato da slide didattiche e ampliato con esempi riproducibili. Tutto il codice è commentato in italiano.


In [2]:

# Setup: import e opzioni di stampa
import numpy as np

# Per riproducibilità nei random
rng = np.random.default_rng(42)

np.__version__


'2.3.1'


## 1) Introduzione a NumPy
NumPy fornisce l'oggetto `ndarray`: un buffer denso di **tipo fisso** (tutti gli elementi dello stesso dtype), in **memoria contigua** e con **N dimensioni**.
Questo è fondamentale per l'**efficienza** rispetto alle liste Python (che sono eterogenee e puntano a oggetti).

Punti chiave:
- Tipi numerici: `int8/16/32/64`, `uint*`, `float16/32/64`, `bool`.
- Array = dati + metadati (shape, strides, dtype).
- Operazioni vettorializzate: molto più veloci dei loop Python.


## 2) Creazione di array

In [3]:

# Da lista Python (con dtype inferito o esplicito)
a = np.array([1, 2, 3])                  # dtype inferito (di solito int64/int32)
b = np.array([1., 2., 3.], dtype=np.float32)  # dtype definito
a, a.dtype, b, b.dtype


(array([1, 2, 3]),
 dtype('int64'),
 array([1., 2., 3.], dtype=float32),
 dtype('float32'))

In [4]:

# Costruttori "da zero"
z = np.zeros((2,3))
o = np.ones((2,3))
f = np.full((2,1), 1.1)
lin = np.linspace(0, 1, 11)        # include 0 e 1, 11 punti
ar = np.arange(1, 7, 2)            # [1, 3, 5]
gauss = rng.normal(loc=0, scale=1, size=(2,3))   # normale
unif = rng.random((2,3))                          # uniforme [0,1)
z, o, f, lin, ar, gauss, unif


(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[1.1],
        [1.1]]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 array([1, 3, 5]),
 array([[ 0.30471708, -1.03998411,  0.7504512 ],
        [ 0.94056472, -1.95103519, -1.30217951]]),
 array([[0.7611397 , 0.78606431, 0.12811363],
        [0.45038594, 0.37079802, 0.92676499]]))

## 3) Attributi principali

In [5]:

x = np.array([[2,3,4],[5,6,7]])
(x.ndim, x.shape, x.size, x.dtype)


(2, (2, 3), 6, dtype('int64'))

## 4) Ufunc (operazioni element‑wise)

In [6]:

x = np.array([[1,1],[2,2]], dtype=float)
y = np.array([[3,4],[6,5]], dtype=float)

# Operazioni binarie element-wise
somma = x + y
prodotto = x * y
divisione = y / x
potenza = x ** 2

# Operazioni unarie
exp_x = np.exp(x)
log_y = np.log(y)
sin_x = np.sin(x)

somma, prodotto, divisione, potenza, exp_x, log_y, sin_x


(array([[4., 5.],
        [8., 7.]]),
 array([[ 3.,  4.],
        [12., 10.]]),
 array([[3. , 4. ],
        [3. , 2.5]]),
 array([[1., 1.],
        [4., 4.]]),
 array([[2.71828183, 2.71828183],
        [7.3890561 , 7.3890561 ]]),
 array([[1.09861229, 1.38629436],
        [1.79175947, 1.60943791]]),
 array([[0.84147098, 0.84147098],
        [0.90929743, 0.90929743]]))

## 5) Aggregazioni e argmin/argmax (anche sugli assi)

In [7]:

x = np.array([[1,1],[2,2]])
tot = x.sum()             # somma totale
media = x.mean()          # media totale
std = x.std()             # deviazione standard
pos_min_flat = x.argmin() # indice nel flatten
pos_max_col = x.argmax(axis=0)  # per colonna
somma_righe = x.sum(axis=1)     # somma per riga
tot, media, std, pos_min_flat, pos_max_col, somma_righe


(np.int64(6),
 np.float64(1.5),
 np.float64(0.5),
 np.int64(0),
 array([1, 1]),
 array([2, 4]))

## 6) Ordinamento (sort, argsort)

In [8]:

x = np.array([[2,1,3],[7,9,8]])
x_sorted_rows = np.sort(x)                     # di default lungo axis=-1 (per righe)
x_sorted_cols = np.sort(x, axis=0)             # per colonne
x_idx_sorted_rows = np.argsort(x)              # indici dell'ordinamento per riga
# Attenzione: x.sort() modifica in place
x_copy = x.copy()
x_copy.sort(axis=1)
x, x_sorted_rows, x_sorted_cols, x_idx_sorted_rows, x_copy


(array([[2, 1, 3],
        [7, 9, 8]]),
 array([[1, 2, 3],
        [7, 8, 9]]),
 array([[2, 1, 3],
        [7, 9, 8]]),
 array([[1, 0, 2],
        [0, 2, 1]]),
 array([[1, 2, 3],
        [7, 8, 9]]))

## 7) Algebra lineare: `@` (prodotto scalare, matrice‑vettore, matrice‑matrice)

In [9]:

# Vettore · vettore => scalare
v1 = np.array([1,2,3])
v2 = np.array([0,2,1])
dot_v = v1 @ v2

# Matrice · vettore => vettore
M = np.array([[1,1],[2,2]])
vec = np.array([2,3])
Mv = M @ vec

# Matrice · matrice => matrice
A = np.array([[1,1],[2,2]])
B = np.array([[2,2],[1,1]])
AB = A @ B

dot_v, Mv, AB


(np.int64(7),
 array([ 5, 10]),
 array([[3, 3],
        [6, 6]]))

## 8) Broadcasting: regole ed esempi

In [10]:

# Esempio 1: somma tra vettore riga (1,3) e vettore colonna (3,1) => matrice (3,3)
x = np.array([1,2,3])            # shape (3,)
y = np.array([[11],[12],[13]])   # shape (3,1)
z = x + y                         # broadcasting: (1,3) + (3,1) -> (3,3)
x.shape, y.shape, z.shape, z


((3,),
 (3, 1),
 (3, 3),
 array([[12, 13, 14],
        [13, 14, 15],
        [14, 15, 16]]))

In [11]:

# Esempio 2: caso incompatibile -> solleva ValueError
X = np.array([[1,2],[3,4],[5,6]])   # shape (3,2)
Y = np.array([11,12,13])            # shape (3,)
error_msg = None
try:
    Z = X + Y
except ValueError as e:
    error_msg = str(e)
error_msg


'operands could not be broadcast together with shapes (3,2) (3,) '

## 9) Accesso agli array: indicizzazione, slicing, masking, fancy indexing

In [12]:

X = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Indicizzazione semplice
el = X[1,2]        # riga 1, colonna 2 (0-based) => 6
X_mod = X.copy()
X_mod[1,2] = 10

# Slicing (view: modifica l'originale)
view = X[:, 1:]    # tutte le righe, dalla colonna 1 in poi
X_view_edit = X.copy()
X_view = X_view_edit[:, 1:]
X_view[:,:] = 0    # azzera le colonne 1..end nell'array originale

# Per evitare effetti collaterali fare copy()
only_copy = X[:,1:].copy()
only_copy[:,:] = -1  # NON modifica X

(el, X_mod, view, X_view_edit, only_copy, X)


(np.int64(6),
 array([[ 1,  2,  3],
        [ 4,  5, 10],
        [ 7,  8,  9]]),
 array([[2, 3],
        [5, 6],
        [8, 9]]),
 array([[1, 0, 0],
        [4, 0, 0],
        [7, 0, 0]]),
 array([[-1, -1],
        [-1, -1],
        [-1, -1]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [13]:

# Masking (booleans): selezione e assegnazione
x = np.array([1.2, 4.1, 1.5, 4.5])
mask = x > 4
sel = x[mask]          # copia 1D con i valori che soddisfano la condizione
x_assign = x.copy()
x_assign[mask] = 0     # assegnazione sui soli elementi True
# Le operazioni booleane si fanno con & | ^ ~ (bitwise)
mask_between = (x >= 1) & (x <= 5)
mask, sel, x_assign, mask_between


(array([False,  True, False,  True]),
 array([4.1, 4.5]),
 array([1.2, 0. , 1.5, 0. ]),
 array([ True,  True,  True,  True]))

In [14]:

# Fancy indexing: specifica esplicita degli indici
x = np.array([7.0, 9.0, 6.0, 5.0])
sel = x[[1,3]]          # prende elementi 1 e 3
X = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
righe_12 = X[[1,2]]     # seleziona righe 1 e 2
coord = X[[1,2],[0,2]]  # coordinate (1,0) e (2,2) => [3., 8.]
# Attenzione: il risultato di masking/fancy è una COPIA (non view)
tmp = x.copy()
tmp2 = tmp[[1,3]]
tmp2[:] = 0
(tmp, sel, righe_12, coord, tmp2, tmp)  # tmp resta invariato


(array([7., 9., 6., 5.]),
 array([9., 5.]),
 array([[3., 4., 5.],
        [6., 7., 8.]]),
 array([3., 8.]),
 array([0., 0.]),
 array([7., 9., 6., 5.]))

In [15]:

# Combined indexing: mix slicing + masking/fancy, e regola sulla riduzione dimensionale
X = np.array([[0.,1.,2.],[3.,4.,5.],[6.,7.,8.]])
m_s = X[[True, False, True], 1:]  # masking + slicing: mantiene numero di dimensioni
f_s = X[[0,2], :2]                # fancy + slicing
s_s = X[0, 1:]                    # simple + slicing: riduce una dimensione (risultato 1D)
X, m_s, f_s, s_s


(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([[1., 2.],
        [7., 8.]]),
 array([[0., 1.],
        [6., 7.]]),
 array([1., 2.]))

## 10) Lavorare con gli array: concatenazione, split, reshape, nuove dimensioni

In [16]:

# Concatenazione
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,12,13],[14,15,16]])
cat0 = np.concatenate((x,y), axis=0)  # per righe
cat1 = np.concatenate((x,y), axis=1)  # per colonne
h = np.hstack((x,y))
v = np.vstack((x,y))
cat0, cat1, h, v


(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 13],
        [14, 15, 16]]),
 array([[ 1,  2,  3, 11, 12, 13],
        [ 4,  5,  6, 14, 15, 16]]),
 array([[ 1,  2,  3, 11, 12, 13],
        [ 4,  5,  6, 14, 15, 16]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [11, 12, 13],
        [14, 15, 16]]))

In [17]:

# vstack su vettori 1D crea un nuovo asse verticale
x = np.array([1,2,3])
y = np.array([11,12,13])
v = np.vstack((x,y))
v, v.shape


(array([[ 1,  2,  3],
        [11, 12, 13]]),
 (2, 3))

In [18]:

# Split (in posizioni o numero di blocchi)
x = np.array([7, 7, 9, 9, 8, 8])
s1, s2, s3 = np.split(x, [2,4])   # davanti a indici 2 e 4
s1, s2, s3


(array([7, 7]), array([9, 9]), array([8, 8]))

In [19]:

# hsplit / vsplit su 2D
X = np.array([[1,2,3,11,12,13],[4,5,6,14,15,16]])
hs = np.hsplit(X, [3])   # splittra colonne in [0:3] e [3:end]
vs = np.vsplit(X, 2)     # splittra righe in 2 blocchi uguali
hs, vs


([array([[1, 2, 3],
         [4, 5, 6]]),
  array([[11, 12, 13],
         [14, 15, 16]])],
 [array([[ 1,  2,  3, 11, 12, 13]]), array([[ 4,  5,  6, 14, 15, 16]])])

In [20]:

# Reshape: ri‑indicizza senza copiare (quando possibile)
x = np.arange(6)         # [0 1 2 3 4 5]
y = x.reshape((2,3))     # 2 righe, 3 colonne
z = np.array([1,2,3]).reshape(-1,1)   # -1 lascia inferire la dimensione
x, y, z, y.flags['C_CONTIGUOUS']


(array([0, 1, 2, 3, 4, 5]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[1],
        [2],
        [3]]),
 True)

In [21]:

# Aggiungere nuove dimensioni con np.newaxis
arr = np.array([[1,2,3],[4,5,6]])
res = arr[np.newaxis, :, :]   # shape (1,2,3)
col = np.array([1,2,3])[:, np.newaxis]  # vettore colonna (3,1)
res.shape, col, col.shape


((1, 2, 3),
 array([[1],
        [2],
        [3]]),
 (3, 1))


## 11) Mini‑esercizi (con soluzioni)
1. **Normalizzazione per colonna** di una matrice `M` (sottrai media e dividi per std per ogni colonna) usando **broadcasting**.
2. Dato `v = [3, 1, 4, 1, 5, 9]`, ordina e recupera gli **indici** dell'ordinamento (argsort). Poi usa questi indici per riordinare `v`.
3. Crea `A` (3×3) e seleziona con **fancy indexing** gli elementi alle coordinate `(0,2)`, `(1,1)`, `(2,0)`.


In [22]:

# 1) Normalizzazione per colonna
M = rng.normal(0, 2, size=(5,4))
mu = M.mean(axis=0)             # (4,)
sd = M.std(axis=0) + 1e-12      # (4,)
M_norm = (M - mu) / sd          # broadcasting (5,4) - (4,) => (5,4)
M, mu, sd, M_norm.mean(axis=0), M_norm.std(axis=0)


(array([[ 0.1320614 ,  2.25448241,  0.93501868, -1.71858493],
        [ 0.73750157, -1.9177652 ,  1.7569006 , -0.09985182],
        [-0.36972473, -1.36185909,  2.44508268, -0.30905896],
        [-0.85665564, -0.7042671 ,  1.06461837,  0.73088813],
        [ 0.82546522,  0.86164201,  4.2832952 , -0.81283003]]),
 array([ 0.09372956, -0.17355339,  2.09698311, -0.44188752]),
 array([0.64333051, 1.52990128, 1.21923978, 0.80964056]),
 array([-4.44089210e-17,  6.66133815e-17,  0.00000000e+00,  1.11022302e-17]),
 array([1., 1., 1., 1.]))

In [23]:

# 2) Ordinamento con argsort e riordinamento
v = np.array([3, 1, 4, 1, 5, 9])
idx = np.argsort(v)
v_sorted = v[idx]
v, idx, v_sorted


(array([3, 1, 4, 1, 5, 9]),
 array([1, 3, 0, 2, 4, 5]),
 array([1, 1, 3, 4, 5, 9]))

In [24]:

# 3) Fancy indexing a coordinate specifiche
A = np.arange(9).reshape(3,3)
coords = A[[0,1,2], [2,1,0]]   # (0,2), (1,1), (2,0)
A, coords


(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([2, 4, 6]))


---

**Suggerimento Pro**: per calcoli intensivi in finanza/ML, valuta dtype `float32` per risparmiare memoria, oppure `float64` per stabilità numerica. Per prodotti complessi considera `np.einsum`/`np.matmul`; per accelerare loop Python esplora `numba`.

*Notebook creato automaticamente.*
